ERR_LOAD_WOPI_BINDINGS = Es konnten nicht alle unterstützten Datei-Typen geladen werden \
                         da der WOPI-Service nicht erreichbar ist.\n\
                         Die Anwendung kann weiter benutzt werden, es ist jedoch möglich das nicht \
                         alle Dateien angezeigt werden können.
