version: "3.6"
services:
  libreoffice-app:
    image: collabora/code:6.4.8.4
    container_name: libreoffice-app
    expose:
      - 9980
    ports:
      - "9980:9980"
    environment:
      username: admin
      password: adminadmin
#      extra_params: "--o:ssl.enable=false --o:ssl.termination=true"
#      DONT_GEN_SSL_CERT: 1
    restart: always
